# Generated by Django 3.1.1 on 2020-09-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200919_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
